### ISSUE TITLE
Build error on unit_test using Ubuntu 18.04 on Docker

### ISSUE THREAD

**Issue by esamson33** [akhin/liteExchange#2]
Since the project does not support Mac, I am using Ubuntu 18.04 on Docker. I use the ff. command to build the unit tests:
> $ cd unit_test
> $ make

This results to an error:

> ...\<snip\>...
> g++ -o ome_unit_test  test.o ../source/core/concurrency/thread.o ../source/core/concurrency/thread_pool.o ../source/core/configuration.o ../source/core/stopwatch.o ../source/core/shared_memory.o ../source/core/logger/logger.o ../source/core/single_instance.o ../source/fix/fix_message.o ../source/order_matcher/order.o ../source/order_matcher/order_book.o ../source/order_matcher/security_manager.o ../source/order_matcher/central_order_book.o  -lstdc++ -pthread google_test/lib/gtest_main.a
> /usr/bin/ld: google_test/lib/gtest_main.a(gtest-all.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
> /usr/bin/ld: google_test/lib/gtest_main.a(gtest_main.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIC
test.o: In function `Utility_SingleInstance_Test::TestBody()':
> /root/Projects/liteExchange/unit_test/test_utility.h:13: undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
test.o: In function `Fix_FixMessage_Test::TestBody()':
> /root/Projects/liteExchange/unit_test/test_fix.h:21: undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
> /root/Projects/liteExchange/unit_test/test_fix.h:22: undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
> /root/Projects/liteExchange/unit_test/test_fix.h:23: undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
> /root/Projects/liteExchange/unit_test/test_fix.h:24: undefined reference to `testing::internal::GetBoolAssertionFailureMessage[abi:cxx11](testing::AssertionResult const&, char const*, char const*, char const*)'
> test.o: In function `testing::AssertionResult testing::internal::CmpHelperEQ<int, unsigned long>(char const*, char const*, int const&, unsigned long const&)':
> /root/Projects/liteExchange/unit_test/google_test/include/gtest/gtest.h:1460: undefined reference to `testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
test.o: In function `testing::AssertionResult testing::internal::CmpHelperEQ<bool, bool>(char const*, char const*, bool const&, bool const&)':
> /root/Projects/liteExchange/unit_test/google_test/include/gtest/gtest.h:1460: undefined reference to `testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
test.o: In function `testing::AssertionResult testing::internal::CmpHelperEQ<int, int>(char const*, char const*, int const&, int const&)':
> /root/Projects/liteExchange/unit_test/google_test/include/gtest/gtest.h:1460: undefined reference to `testing::internal::EqFailure(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
> /usr/bin/ld: final link failed: Nonrepresentable section on output
> collect2: error: ld returned 1 exit status
> Makefile:42: recipe for target 'ome_unit_test' failed
> make: *** [ome_unit_test] Error 1

@akhin Hope you can shed some light. Thanks!

**Comment by akhin** [comment]
Thanks for pointing out , made an update , hopefully should be fixed now. Could you let me know if you can try ?

**Comment by esamson33** [comment]
Tried it again, and build, unit tests were good.
